/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.coffemachine;

import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author omarj
 */
public class CoffemachineJframe extends javax.swing.JFrame {
    
           ArrayList<String> coffes=new ArrayList<>();
           List<String> list=new LinkedList<>();
           ArrayList<Date> dateList = new ArrayList<>();
           ArrayList<Integer> numberList = new ArrayList<>();
           ArrayList<Beans>bean=new ArrayList<>();
           ArrayList<WaterTank>wate=new ArrayList<>();
           ArrayList<Espresso>espress=new ArrayList<>();
           ArrayList<Americano>american=new ArrayList<>();
           Date currentDate = new Date();
           Random rand = new Random();

    
                Beans B=new Beans();
                Espresso s=new Espresso();
                Americano A=new Americano();
                WaterTank wt=new WaterTank();
                Counter c=new Counter();
                Grind G=new Grind();
                Machine M=new Machine(G,c,250,wt);


    
    int bfv=0;
    
    /**
     * Creates new form CoffemachineJframe
     */
    public CoffemachineJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        FILL = new javax.swing.JButton();
        ON = new javax.swing.JButton();
        PRINTCAFFINEBUTTON = new javax.swing.JButton();
        HOWMANYTEXTFIELD = new javax.swing.JButton();
        REMBUTTON = new javax.swing.JButton();
        CLEANBUTTON = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        ONTEXTFIELD = new javax.swing.JTextField();
        FILLTEXTFIELD = new javax.swing.JTextField();
        GRINDTEXTFIELD = new javax.swing.JTextField();
        FLOWRATETEXTFIELD = new javax.swing.JTextField();
        CLEANTEXTFIELD = new javax.swing.JTextField();
        HOWMANYBUTTON = new javax.swing.JButton();
        GRINDBUTTON = new javax.swing.JButton();
        FLOWRATEBUTTON = new javax.swing.JButton();
        EASBUTTON = new javax.swing.JButton();
        EADBUTTON = new javax.swing.JButton();
        ERSBUTTON = new javax.swing.JButton();
        ERDBUTTON = new javax.swing.JButton();
        AASBUTTON = new javax.swing.JButton();
        AADBUTTON = new javax.swing.JButton();
        ARSBUTTON = new javax.swing.JButton();
        ARDBUTTON = new javax.swing.JButton();
        CAFFINETEXTFIELD = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListData = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListData2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListData3 = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListData4 = new javax.swing.JList<>();
        jMenuBar2 = new javax.swing.JMenuBar();
        exit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Turn on Machine");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Fill The Machine");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("                                                                                Make cup of coffe");
        jLabel3.setToolTipText("");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel4.setText("Print caffine of the last cup");

        jLabel5.setText("Print how many coffe we've made");

        jLabel6.setText("Prints Bean and water remaining");

        jLabel7.setText("Clean the Machine");

        jLabel8.setText("Grind size control");

        jLabel9.setText("Adjust the flowrate speed");

        jLabel10.setText("Turn Off Machine");

        FILL.setText("Fill");
        FILL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FILLActionPerformed(evt);
            }
        });

        ON.setText("ON");
        ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONActionPerformed(evt);
            }
        });

        PRINTCAFFINEBUTTON.setText("Print");
        PRINTCAFFINEBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRINTCAFFINEBUTTONActionPerformed(evt);
            }
        });

        HOWMANYTEXTFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOWMANYTEXTFIELDActionPerformed(evt);
            }
        });

        REMBUTTON.setText("Print");
        REMBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMBUTTONActionPerformed(evt);
            }
        });

        CLEANBUTTON.setText("Clean");
        CLEANBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEANBUTTONActionPerformed(evt);
            }
        });

        jButton13.setText("OFF");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        HOWMANYBUTTON.setText("Print");
        HOWMANYBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOWMANYBUTTONActionPerformed(evt);
            }
        });

        GRINDBUTTON.setText("Add");
        GRINDBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRINDBUTTONActionPerformed(evt);
            }
        });

        FLOWRATEBUTTON.setText("Add");
        FLOWRATEBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FLOWRATEBUTTONActionPerformed(evt);
            }
        });

        EASBUTTON.setText("Espres-arab-single");
        EASBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EASBUTTONActionPerformed(evt);
            }
        });

        EADBUTTON.setText("Espres-arab-double");
        EADBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EADBUTTONActionPerformed(evt);
            }
        });

        ERSBUTTON.setText("Espres-robu-single");
        ERSBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ERSBUTTONActionPerformed(evt);
            }
        });

        ERDBUTTON.setText("Espres-robu-doubl");
        ERDBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ERDBUTTONActionPerformed(evt);
            }
        });

        AASBUTTON.setText("Americ-arab-single");
        AASBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AASBUTTONActionPerformed(evt);
            }
        });

        AADBUTTON.setText("Americ-arab-doub");
        AADBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AADBUTTONActionPerformed(evt);
            }
        });

        ARSBUTTON.setText("Americ-robu-sing");
        ARSBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ARSBUTTONActionPerformed(evt);
            }
        });

        ARDBUTTON.setText("Americ-robu-doubl");
        ARDBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ARDBUTTONActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 51, 51));

        jSeparator3.setForeground(new java.awt.Color(204, 0, 0));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("                                                   Proprties");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AASBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(80, 80, 80))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(30, 30, 30)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PRINTCAFFINEBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                .addComponent(REMBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CLEANBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FILL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HOWMANYBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GRINDBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FLOWRATEBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CLEANTEXTFIELD)
                                    .addComponent(HOWMANYTEXTFIELD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(GRINDTEXTFIELD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FLOWRATETEXTFIELD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CAFFINETEXTFIELD))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ONTEXTFIELD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FILLTEXTFIELD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AADBUTTON)
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ARSBUTTON)
                            .addComponent(ERSBUTTON, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ARDBUTTON, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ERDBUTTON, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EASBUTTON)
                        .addGap(74, 74, 74)
                        .addComponent(EADBUTTON))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ON)
                    .addComponent(jLabel1)
                    .addComponent(ONTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FILL)
                    .addComponent(FILLTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EASBUTTON)
                    .addComponent(EADBUTTON)
                    .addComponent(ERSBUTTON)
                    .addComponent(ERDBUTTON))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AADBUTTON)
                            .addComponent(ARDBUTTON)
                            .addComponent(ARSBUTTON)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(AASBUTTON)))
                .addGap(21, 21, 21)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PRINTCAFFINEBUTTON)
                    .addComponent(CAFFINETEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(HOWMANYBUTTON))
                    .addComponent(HOWMANYTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(REMBUTTON))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CLEANBUTTON)
                    .addComponent(CLEANTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(GRINDTEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GRINDBUTTON))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(FLOWRATETEXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FLOWRATEBUTTON))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jButton13))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("tab1", jPanel5);

        ListData.setBorder(javax.swing.BorderFactory.createTitledBorder("Espresso"));
        ListData.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListDataValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListData);

        ListData2.setBorder(javax.swing.BorderFactory.createTitledBorder("Americanos"));
        ListData2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListData2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ListData2);

        ListData3.setBorder(javax.swing.BorderFactory.createTitledBorder("Beans Remaining"));
        jScrollPane3.setViewportView(ListData3);
        ListData3.getAccessibleContext().setAccessibleName("Beans remaining");

        ListData4.setBorder(javax.swing.BorderFactory.createTitledBorder("Water Remaining"));
        jScrollPane4.setViewportView(ListData4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("tab2", jPanel6);

        exit.setText("Option");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        exit.add(jMenuItem1);

        jMenuBar2.add(exit);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// hereeee00000000000000000
    DefaultListModel dm=new DefaultListModel();
void display()
{
    String[] arr=new String[espress.size()];
    for(int i=0;i<espress.size();i++)
    {
        arr[i]=espress.get(i).toString();
    }
    
   ListData.setListData(arr);
    System.out.println("");
}   
    void display1(){
        String [] arr1 = new String[american.size()];
        for (int i = 0; i < american.size(); i++) {
            
            arr1[i]= american.get(i).toString();
        }
        ListData2.setListData(arr1);
        System.out.println("");
    }
    void display2()
    {
        String [] arr2=new String[bean.size()];
        for(int i=0;i<bean.size();i++)
        {
            arr2[i]=bean.get(i).getInfo();
        }
        ListData3.setListData(arr2);
        System.out.println("");
    }
    void display3()
    {
        String [] arr3=new String[wate.size()];
        for(int i=0;i<wate.size();i++)
        {
            arr3[i]=wate.get(i).getInfo();
        }
        ListData4.setListData(arr3);
        System.out.println("");
    }

    
    
    
    
    
    
    private void ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONActionPerformed
        // TODO add your handling code here:

        ON.setEnabled(true);
        ONTEXTFIELD.setText("Machine progress....Done");

        
        
    }//GEN-LAST:event_ONActionPerformed

    private void FILLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FILLActionPerformed
        // TODO add your handling code here:
                B.set(80,80);
                wt.setWater(599);
                FILLTEXTFIELD.setText("Filled...Done");
                ONTEXTFIELD.setText("");

                

        
    }//GEN-LAST:event_FILLActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void CLEANBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEANBUTTONActionPerformed
        // TODO add your handling code here:
                B.set(0,0);
                M.getWet().setWater(0);
               CLEANTEXTFIELD.setText("Cleaning completed");
               HOWMANYTEXTFIELD.setText(" ");
               ONTEXTFIELD.setText(" ");
               FILLTEXTFIELD.setText(" ");
               CAFFINETEXTFIELD.setText(" ");
               FLOWRATETEXTFIELD.setText(" ");
               GRINDTEXTFIELD.setText(" ");

    }//GEN-LAST:event_CLEANBUTTONActionPerformed

    private void ListDataValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListDataValueChanged
        // TODO add your handling code here:
        int index=ListData.getSelectedIndex();
        if(index!=-1)
        {
     JOptionPane.showMessageDialog(this,espress.get(index).getInfo1());

            
        }
    }//GEN-LAST:event_ListDataValueChanged

    private void HOWMANYBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOWMANYBUTTONActionPerformed
        // TODO add your handling code here:
        HOWMANYTEXTFIELD.setText(c.getCounter()+" ");
    }//GEN-LAST:event_HOWMANYBUTTONActionPerformed

    private void GRINDBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRINDBUTTONActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Grind size Done");
    }//GEN-LAST:event_GRINDBUTTONActionPerformed

    private void REMBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMBUTTONActionPerformed
        // TODO add your handling code here:
        bean.add(B);
        wate.add(wt);
        display2();
        display3();
    }//GEN-LAST:event_REMBUTTONActionPerformed

    private void EADBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EADBUTTONActionPerformed
bfv=1;                      wt.drainWater(60);
                          B.drainArabica(14);
       c.counter();
       // Espresso str=new Espresso(B.amount_of_Arabica,B.amount_of_Robusta);
      espress.add(s);
        display();
        // TODO add your handling code here:
    }//GEN-LAST:event_EADBUTTONActionPerformed

    private void EASBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EASBUTTONActionPerformed
                      wt.drainWater(30);
        // TODO add your handling code here:
                                  B.drainArabica(7);

       // Espresso str=new Espresso(B.amount_of_Arabica,B.amount_of_Robusta);
       c.counter();
      espress.add(s);
        display();
    }//GEN-LAST:event_EASBUTTONActionPerformed

    private void ERSBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ERSBUTTONActionPerformed
bfv=2;                      wt.drainWater(30);
                          B.drainRobusta(7);
       c.counter();
     //   Espresso str=new Espresso(B.amount_of_Arabica,B.amount_of_Robusta);
      espress.add(s);
        display();
        // TODO add your handling code here:
    }//GEN-LAST:event_ERSBUTTONActionPerformed

    private void ERDBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ERDBUTTONActionPerformed
bfv=3;                      wt.drainWater(60);
                          B.drainRobusta(14);
       c.counter();
       // Espresso str=new Espresso(B.amount_of_Arabica,B.amount_of_Robusta);
      espress.add(s);
        display();
        // TODO add your handling code here:
    }//GEN-LAST:event_ERDBUTTONActionPerformed

    private void AASBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AASBUTTONActionPerformed
bfv=4;                      wt.drainWater(170);
                          B.drainArabica(7);
       c.counter();
        // TODO add your handling code here:
       
        american.add(A);
        display1();
        
    }//GEN-LAST:event_AASBUTTONActionPerformed

    private void AADBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AADBUTTONActionPerformed
bfv=5;                      wt.drainWater(220);
           B.drainArabica(14);
       c.counter();
        // TODO add your handling code here:
        american.add(A);
        display1();

        
    }//GEN-LAST:event_AADBUTTONActionPerformed

    private void ARSBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ARSBUTTONActionPerformed
bfv=6;                      wt.drainWater(170);
                          B.drainRobusta(7);
       c.counter();
        // TODO add your handling code here:
                american.add(A);
        display1();

    }//GEN-LAST:event_ARSBUTTONActionPerformed

    private void ARDBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ARDBUTTONActionPerformed
bfv=7;                      wt.drainWater(220);
                          B.drainRobusta(14);
       c.counter();
        // TODO add your handling code here:
                american.add(A);
        display1();

    }//GEN-LAST:event_ARDBUTTONActionPerformed

    private void ListData2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListData2ValueChanged
        // TODO add your handling code here:
        int index=ListData.getSelectedIndex();
        if(index!=-1)
        {
            JOptionPane.showMessageDialog(this,american.get(index).GETINFO());
        }
        
        
        
        
        
        
    }//GEN-LAST:event_ListData2ValueChanged

    private void FLOWRATEBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FLOWRATEBUTTONActionPerformed
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(this,"ADjust flow ratespeed Done");

    }//GEN-LAST:event_FLOWRATEBUTTONActionPerformed

    private void PRINTCAFFINEBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRINTCAFFINEBUTTONActionPerformed
        if(bfv==0)
        {
            CAFFINETEXTFIELD.setText(""+90);
        }
        else if(bfv==1)
        {
          CAFFINETEXTFIELD.setText(""+130);

        }
        else if(bfv==2)
        {
            CAFFINETEXTFIELD.setText(""+125);
        }
        else if(bfv==3)
        {
            CAFFINETEXTFIELD.setText(""+180);
        }
        else if(bfv==4)
        {
            CAFFINETEXTFIELD.setText(""+60);
        }
        else if(bfv==5)
        {
            CAFFINETEXTFIELD.setText(""+80);
        }
        else if(bfv==6)
        {
            CAFFINETEXTFIELD.setText(""+122);
        }
        else 
        {
            CAFFINETEXTFIELD.setText(""+154);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_PRINTCAFFINEBUTTONActionPerformed

    private void HOWMANYTEXTFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOWMANYTEXTFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HOWMANYTEXTFIELDActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffemachineJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffemachineJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffemachineJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffemachineJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffemachineJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AADBUTTON;
    private javax.swing.JButton AASBUTTON;
    private javax.swing.JButton ARDBUTTON;
    private javax.swing.JButton ARSBUTTON;
    private javax.swing.JTextField CAFFINETEXTFIELD;
    private javax.swing.JButton CLEANBUTTON;
    private javax.swing.JTextField CLEANTEXTFIELD;
    private javax.swing.JButton EADBUTTON;
    private javax.swing.JButton EASBUTTON;
    private javax.swing.JButton ERDBUTTON;
    private javax.swing.JButton ERSBUTTON;
    private javax.swing.JButton FILL;
    private javax.swing.JTextField FILLTEXTFIELD;
    private javax.swing.JButton FLOWRATEBUTTON;
    private javax.swing.JTextField FLOWRATETEXTFIELD;
    private javax.swing.JButton GRINDBUTTON;
    private javax.swing.JTextField GRINDTEXTFIELD;
    private javax.swing.JButton HOWMANYBUTTON;
    private javax.swing.JButton HOWMANYTEXTFIELD;
    private javax.swing.JList<String> ListData;
    private javax.swing.JList<String> ListData2;
    private javax.swing.JList<String> ListData3;
    private javax.swing.JList<String> ListData4;
    private javax.swing.JButton ON;
    private javax.swing.JTextField ONTEXTFIELD;
    private javax.swing.JButton PRINTCAFFINEBUTTON;
    private javax.swing.JButton REMBUTTON;
    private javax.swing.JMenu exit;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
